"""
ClassRoom Manager - Sabitlər və ümumi konfiqurasiya dəyərləri.
"""

APP_NAME = "ClassRoom Manager"
APP_VERSION = "1.0.0"

# Şəbəkə
DEFAULT_PORT = 11100
BUFFER_SIZE = 65536
HEADER_SIZE = 10  # Mesaj uzunluğu üçün header (bayt)

# Screenshot
DEFAULT_SCREENSHOT_INTERVAL = 3  # saniyə
DEFAULT_SCREENSHOT_QUALITY = 50  # JPEG keyfiyyəti (1-100)
DEFAULT_THUMBNAIL_WIDTH = 320
DEFAULT_THUMBNAIL_HEIGHT = 180

# Demo
DEFAULT_DEMO_FPS = 10
DEFAULT_DEMO_QUALITY = 60

# Heartbeat
DEFAULT_HEARTBEAT_INTERVAL = 5  # saniyə
HEARTBEAT_TIMEOUT = 15  # saniyə - bu müddətdə cavab gəlməsə offline sayılır

# Fayl ötürmə
FILE_CHUNK_SIZE = 65536  # 64KB

# Agent
DEFAULT_FILE_SAVE_PATH = "~/Desktop/ClassRoom"

# Mesaj tipləri
class MessageType:
    REGISTER = "REGISTER"
    REGISTER_ACK = "REGISTER_ACK"
    HEARTBEAT = "HEARTBEAT"
    HEARTBEAT_ACK = "HEARTBEAT_ACK"
    SCREENSHOT = "SCREENSHOT"
    SCREENSHOT_REQUEST = "SCREENSHOT_REQUEST"
    LOCK_SCREEN = "LOCK_SCREEN"
    UNLOCK_SCREEN = "UNLOCK_SCREEN"
    LOCK_INPUT = "LOCK_INPUT"
    UNLOCK_INPUT = "UNLOCK_INPUT"
    START_DEMO = "START_DEMO"
    STOP_DEMO = "STOP_DEMO"
    DEMO_FRAME = "DEMO_FRAME"
    SEND_MESSAGE = "SEND_MESSAGE"
    FILE_TRANSFER = "FILE_TRANSFER"
    FILE_CHUNK = "FILE_CHUNK"
    FILE_COMPLETE = "FILE_COMPLETE"
    COLLECT_FILE = "COLLECT_FILE"
    SHUTDOWN = "SHUTDOWN"
    RESTART = "RESTART"
    RUN_PROGRAM = "RUN_PROGRAM"
    OPEN_URL = "OPEN_URL"
    DISCONNECT = "DISCONNECT"
    # Uzaqdan müdaxilə
    REMOTE_CONTROL_START = "REMOTE_CONTROL_START"
    REMOTE_CONTROL_STOP = "REMOTE_CONTROL_STOP"
    REMOTE_MOUSE_EVENT = "REMOTE_MOUSE_EVENT"
    REMOTE_KEY_EVENT = "REMOTE_KEY_EVENT"
    REMOTE_SCREENSHOT_REQUEST = "REMOTE_SCREENSHOT_REQUEST"
    REMOTE_SCREENSHOT = "REMOTE_SCREENSHOT"
